#!/usr/bin/env python3
"""
Week 11 - Explanation Quality Analysis

Analyzes the quality of explanations generated by the system using multiple metrics:
- Correctness (matching expected concepts)
- Clarity (readability scores)
- Completeness (coverage of key points)
- Security awareness (security concepts mentioned)
"""

import json
import re
from pathlib import Path
from typing import Dict, List, Tuple
from explain_error import get_explanation_for_error, generate_explanation, format_error
from security_explainer import analyze_security_implications


class ExplanationQualityAnalyzer:
    """Analyzes quality of generated explanations."""
    
    # Expected concepts for different error types
    EXPECTED_CONCEPTS = {
        "type_mismatch": ["type", "incompatible", "assignment", "conversion", "data type"],
        "undeclared": ["declare", "undefined", "not declared", "scope", "identifier"],
        "format_string": ["format", "specifier", "type", "argument", "printf"],
        "unused_result": ["return value", "unused", "check", "error handling"],
        "implicit_conversion": ["implicit", "conversion", "cast", "type", "precision"],
        "sign_compare": ["signed", "unsigned", "comparison", "different signs"],
        "buffer_overflow": ["buffer", "overflow", "bounds", "size", "strcpy"],
        "null_pointer": ["null", "pointer", "check", "allocation", "valid"],
        "memory_leak": ["memory", "leak", "free", "allocation", "deallocation"],
        "uninitialized": ["uninitialized", "garbage value", "initialize", "default"],
        "empty_body": ["semicolon", "loop body", "infinite loop", "nothing"],
        "assignment_condition": ["assignment", "equality", "double equals", "instead of"],
        "string_comparison": ["strcmp", "address", "content", "pointer"],
        "sizeof_array_param": ["pointer", "size", "bytes", "parameter"]
    }
    
    # Security concepts that should be mentioned
    SECURITY_CONCEPTS = [
        "vulnerability", "security", "overflow", "exploit", "unsafe",
        "dangerous", "risk", "attack", "malicious", "input validation",
        "bounds checking", "null check", "error handling"
    ]
    
    # Readability thresholds
    READABILITY_THRESHOLDS = {
        "excellent": {"min_words": 15, "max_words": 50, "complexity": "low"},
        "good": {"min_words": 10, "max_words": 75, "complexity": "medium"},
        "acceptable": {"min_words": 5, "max_words": 100, "complexity": "high"}
    }
    
    def __init__(self):
        self.analysis_results = []
    
    def generate_explanation(self, error_message: str, code_context: str = "") -> str:
        """Generate explanation using the explain_error module."""
        # Try rule-based first
        explanation = get_explanation_for_error(error_message)
        return explanation
    
    def calculate_readability(self, text: str) -> Dict:
        """Calculate readability metrics for text."""
        words = text.split()
        sentences = re.split(r'[.!?]+', text)
        sentences = [s for s in sentences if s.strip()]
        
        word_count = len(words)
        sentence_count = len(sentences)
        avg_words_per_sentence = word_count / max(sentence_count, 1)
        
        # Simple complexity estimate (longer words = more complex)
        complex_words = sum(1 for w in words if len(w) > 8)
        complexity_ratio = complex_words / max(word_count, 1)
        
        # Flesch-like readability score (simplified)
        readability_score = 100 - (avg_words_per_sentence * 1.5) - (complexity_ratio * 100)
        readability_score = max(0, min(100, readability_score))
        
        return {
            "word_count": word_count,
            "sentence_count": sentence_count,
            "avg_words_per_sentence": round(avg_words_per_sentence, 2),
            "complexity_ratio": round(complexity_ratio, 2),
            "readability_score": round(readability_score, 2),
            "rating": self._get_readability_rating(readability_score)
        }
    
    def _get_readability_rating(self, score: float) -> str:
        """Get readability rating from score."""
        if score >= 70:
            return "excellent"
        elif score >= 50:
            return "good"
        elif score >= 30:
            return "acceptable"
        else:
            return "poor"
    
    def check_correctness(self, explanation: str, error_type: str) -> Dict:
        """Check if explanation contains expected concepts."""
        explanation_lower = explanation.lower()
        expected = self.EXPECTED_CONCEPTS.get(error_type, [])
        
        if not expected:
            # Generic check for any relevant concepts
            all_concepts = []
            for concepts in self.EXPECTED_CONCEPTS.values():
                all_concepts.extend(concepts)
            expected = list(set(all_concepts))[:10]
        
        matched_concepts = []
        missing_concepts = []
        
        for concept in expected:
            if concept.lower() in explanation_lower:
                matched_concepts.append(concept)
            else:
                missing_concepts.append(concept)
        
        coverage = len(matched_concepts) / max(len(expected), 1)
        
        return {
            "expected_concepts": expected,
            "matched_concepts": matched_concepts,
            "missing_concepts": missing_concepts,
            "coverage": round(coverage * 100, 2),
            "correctness_rating": self._get_correctness_rating(coverage)
        }
    
    def _get_correctness_rating(self, coverage: float) -> str:
        """Get correctness rating from coverage."""
        if coverage >= 0.8:
            return "excellent"
        elif coverage >= 0.6:
            return "good"
        elif coverage >= 0.4:
            return "acceptable"
        else:
            return "poor"
    
    def check_security_awareness(self, explanation: str, code_context: str = "") -> Dict:
        """Check if explanation includes security awareness."""
        text_lower = (explanation + " " + code_context).lower()
        
        security_mentions = []
        for concept in self.SECURITY_CONCEPTS:
            if concept.lower() in text_lower:
                security_mentions.append(concept)
        
        # Also check using security explainer
        security_analysis = analyze_security_implications(explanation, code_context)
        has_security_analysis = security_analysis is not None
        
        return {
            "security_mentions": security_mentions,
            "security_mention_count": len(security_mentions),
            "has_formal_security_analysis": has_security_analysis,
            "security_rating": "high" if len(security_mentions) >= 3 else 
                              "medium" if len(security_mentions) >= 1 else "low"
        }
    
    def check_completeness(self, explanation: str) -> Dict:
        """Check if explanation is complete (has problem description and solution)."""
        has_problem = any(word in explanation.lower() for word in 
                         ["error", "issue", "problem", "warning", "incorrect", "wrong"])
        has_solution = any(word in explanation.lower() for word in 
                          ["fix", "solution", "should", "use", "change", "correct", "proper"])
        has_example = any(word in explanation.lower() for word in 
                         ["example", "e.g.", "such as", "like", "for instance"])
        has_explanation = any(word in explanation.lower() for word in 
                             ["because", "this means", "indicates", "caused by", "due to"])
        
        components = {
            "problem_description": has_problem,
            "solution_guidance": has_solution,
            "example_provided": has_example,
            "cause_explanation": has_explanation
        }
        
        completeness_score = sum(components.values()) / len(components)
        
        return {
            "components": components,
            "completeness_score": round(completeness_score * 100, 2),
            "completeness_rating": self._get_completeness_rating(completeness_score)
        }
    
    def _get_completeness_rating(self, score: float) -> str:
        """Get completeness rating from score."""
        if score >= 0.75:
            return "excellent"
        elif score >= 0.5:
            return "good"
        elif score >= 0.25:
            return "acceptable"
        else:
            return "poor"
    
    def analyze_explanation(self, error_message: str, explanation: str, 
                           code_context: str = "", error_type: str = "general") -> Dict:
        """Perform comprehensive quality analysis on an explanation."""
        analysis = {
            "error_message": error_message,
            "error_type": error_type,
            "explanation": explanation,
            "code_context": code_context,
            "readability": self.calculate_readability(explanation),
            "correctness": self.check_correctness(explanation, error_type),
            "security_awareness": self.check_security_awareness(explanation, code_context),
            "completeness": self.check_completeness(explanation),
            "overall_score": 0,
            "overall_rating": ""
        }
        
        # Calculate overall score
        scores = [
            analysis["readability"]["readability_score"] / 20,  # 0-5
            analysis["correctness"]["coverage"] * 5,  # 0-5
            (analysis["security_awareness"]["security_mention_count"] / 3) * 5,  # 0-5
            analysis["completeness"]["completeness_score"] / 20  # 0-5
        ]
        analysis["overall_score"] = round(sum(scores) / len(scores) * 5, 2)
        analysis["overall_rating"] = self._get_overall_rating(analysis["overall_score"])
        
        self.analysis_results.append(analysis)
        return analysis
    
    def _get_overall_rating(self, score: float) -> str:
        """Get overall rating from score."""
        if score >= 4.0:
            return "excellent"
        elif score >= 3.0:
            return "good"
        elif score >= 2.0:
            return "acceptable"
        else:
            return "needs_improvement"
    
    def generate_report(self) -> str:
        """Generate a comprehensive quality analysis report."""
        if not self.analysis_results:
            return "No analysis results available."
        
        report = []
        report.append("=" * 70)
        report.append("EXPLANATION QUALITY ANALYSIS REPORT")
        report.append("=" * 70)
        report.append("")
        
        # Summary statistics
        avg_readability = sum(a["readability"]["readability_score"] for a in self.analysis_results) / len(self.analysis_results)
        avg_correctness = sum(a["correctness"]["coverage"] for a in self.analysis_results) / len(self.analysis_results)
        avg_security = sum(a["security_awareness"]["security_mention_count"] for a in self.analysis_results) / len(self.analysis_results)
        avg_completeness = sum(a["completeness"]["completeness_score"] for a in self.analysis_results) / len(self.analysis_results)
        avg_overall = sum(a["overall_score"] for a in self.analysis_results) / len(self.analysis_results)
        
        report.append("SUMMARY STATISTICS")
        report.append("-" * 50)
        report.append(f"Total Explanations Analyzed: {len(self.analysis_results)}")
        report.append(f"Average Readability Score: {avg_readability:.2f}/5")
        report.append(f"Average Correctness Coverage: {avg_correctness*100:.1f}%")
        report.append(f"Average Security Mentions: {avg_security:.2f} per explanation")
        report.append(f"Average Completeness: {avg_completeness:.1f}%")
        report.append(f"Overall Quality Score: {avg_overall:.2f}/5")
        report.append("")
        
        # Rating distribution
        report.append("RATING DISTRIBUTION")
        report.append("-" * 50)
        ratings = {}
        for a in self.analysis_results:
            rating = a["overall_rating"]
            ratings[rating] = ratings.get(rating, 0) + 1
        
        for rating, count in sorted(ratings.items()):
            bar = "█" * count
            report.append(f"  {rating:20} {bar} ({count})")
        report.append("")
        
        # Detailed results
        report.append("DETAILED RESULTS")
        report.append("-" * 50)
        
        for i, analysis in enumerate(self.analysis_results, 1):
            report.append(f"\n[{i}] Error Type: {analysis['error_type']}")
            report.append(f"    Error: {analysis['error_message'][:60]}...")
            report.append(f"    Overall: {analysis['overall_score']}/5 ({analysis['overall_rating']})")
            report.append(f"    Readability: {analysis['readability']['rating']}")
            report.append(f"    Correctness: {analysis['correctness']['correctness_rating']} ({analysis['correctness']['coverage']}%)")
            report.append(f"    Security: {analysis['security_awareness']['security_rating']}")
            report.append(f"    Completeness: {analysis['completeness']['completeness_rating']}")
        
        report.append("")
        report.append("=" * 70)
        
        return "\n".join(report)
    
    def save_results(self, output_file: str = "quality_analysis_results.json"):
        """Save analysis results to JSON file."""
        with open(output_file, 'w') as f:
            json.dump({
                "summary": {
                    "total_analyzed": len(self.analysis_results),
                    "average_scores": {
                        "readability": sum(a["readability"]["readability_score"] for a in self.analysis_results) / max(len(self.analysis_results), 1),
                        "correctness": sum(a["correctness"]["coverage"] for a in self.analysis_results) / max(len(self.analysis_results), 1),
                        "security": sum(a["security_awareness"]["security_mention_count"] for a in self.analysis_results) / max(len(self.analysis_results), 1),
                        "completeness": sum(a["completeness"]["completeness_score"] for a in self.analysis_results) / max(len(self.analysis_results), 1),
                        "overall": sum(a["overall_score"] for a in self.analysis_results) / max(len(self.analysis_results), 1)
                    }
                },
                "results": self.analysis_results
            }, f, indent=2)


def main():
    """Run quality analysis on sample explanations."""
    analyzer = ExplanationQualityAnalyzer()
    
    # Test cases with expected error types
    test_cases = [
        {
            "error": "warning: implicit conversion from 'int' to 'char'",
            "code": "char c = value;",
            "error_type": "implicit_conversion",
            "expected_explanation": "This error indicates an implicit type conversion that may lose data. The int value is being converted to char without an explicit cast."
        },
        {
            "error": "warning: unused return value of 'read' function",
            "code": "read(fd, buffer, size);",
            "error_type": "unused_result",
            "expected_explanation": "The return value of read() should be checked to handle errors properly. Unchecked return values can lead to using invalid data."
        },
        {
            "error": "warning: format string is not a string literal",
            "code": "printf(user_input);",
            "error_type": "format_string",
            "expected_explanation": "Using user input as a format string is a serious security vulnerability. Always use printf(\"%s\", user_input) instead."
        },
        {
            "error": "error: use of undeclared identifier 'x'",
            "code": "x = 5;",
            "error_type": "undeclared",
            "expected_explanation": "The variable 'x' is being used without being declared first. In C, all variables must be declared with a type before use."
        },
        {
            "error": "warning: comparison of integers of different signs",
            "code": "if (i < len)",
            "error_type": "sign_compare",
            "expected_explanation": "Comparing signed and unsigned integers can cause unexpected behavior. Negative values may be treated as large positive numbers."
        }
    ]
    
    print("=" * 70)
    print("EXPLANATION QUALITY ANALYSIS")
    print("=" * 70)
    print()
    
    for test in test_cases:
        print(f"Analyzing: {test['error_type']}")
        
        # Generate explanation using the system
        explanation = analyzer.generate_explanation(test['error'], test['code'])
        
        # Analyze the explanation
        analysis = analyzer.analyze_explanation(
            test['error'],
            explanation,
            test['code'],
            test['error_type']
        )
        
        print(f"  Overall Score: {analysis['overall_score']}/5 ({analysis['overall_rating']})")
        print(f"  Readability: {analysis['readability']['rating']}")
        print(f"  Correctness: {analysis['correctness']['correctness_rating']}")
        print(f"  Security: {analysis['security_awareness']['security_rating']}")
        print()
    
    # Generate and print report
    report = analyzer.generate_report()
    print(report)
    
    # Save results
    analyzer.save_results()
    print("\n📄 Results saved to: quality_analysis_results.json")


if __name__ == "__main__":
    main()
